apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Release.Namespace }}-app.io
    http:
      paths:
      - path: /
        backend:
          serviceName: habr-demo-app
          servicePort: 8080
